version: '3'

services:

  traefik:
    image: traefik:1.7
    command: --docker --docker.domain=aikopipo.de
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      # - "traefik.frontend.rule=Host:traefik.aikopipo.de"
      # - "traefik.port=8080"

      - "traefik.http.routers.nas.entrypoints=http"
      - "traefik.http.routers.nas.rule=Host:aikopipo.de"
      - "traefik.http.routers.nas.service=nas@file"


    container_name: traefik
    restart: always

networks:
  proxy:
    external: true