#Traefik Global Configuration
checkNewVersion = true
debug = false
logLevel = "ERROR"

#Define the EntryPoint for HTTP and HTTPS
defaultEntryPoints = ["https", "http"]

#Enable Traefik Dashboard on port 8080
#with basic authentication method
#mohammad and password
[web]
address = ":8080"
[web.auth.basic]
users = ["ubuntu:$apr1$hSUuL0gz$Ux0.27vof2P4297HK78P9/"]

#Define the HTTP port 80 and
#HTTPS port 443 EntryPoint
#Enable automatically redirect HTTP to HTTPS
[entryPoints]
[entryPoints.http]
address = ":80"
# [entryPoints.http.redirect]
# entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

# [providers.http]
#   endpoint = "http://aikopipo.de:8030"

[providers.file]
filename = "/home/ubuntu/TraefikConfig/services.toml"

#Enable retry sending a request if the network error
[retry]

#Define Docker Backend Configuration
[docker]
domain = "traefik.aikopipo.de"
endpoint = "unix:///var/run/docker.sock"
exposedbydefault = false
watch = true

#Letsencrypt Registration
#Define the Letsencrypt ACME HTTP challenge
[acme]
OnHostRule = true
email = "aiko.pipo@hotmail.de"
entryPoint = "https"
storage = "acme.json"
[acme.httpChallenge]
entryPoint = "http"
