# #Traefik Global Configuration
# checkNewVersion = true
# debug = true
# logLevel = "INFO"

#Define the EntryPoint for HTTP and HTTPS
# defaultEntryPoints = ["https", "http"]

#Enable Traefik Dashboard on port 8080
#with basic authentication method
#mohammad and password
# [web]
# address = ":8080"

# [web.auth.basic]
# users = ["ubuntu:$apr1$hSUuL0gz$Ux0.27vof2P4297HK78P9/"]

#Define the HTTP port 80 and
#HTTPS port 443 EntryPoint
#Enable automatically redirect HTTP to HTTPS
[entryPoints]
    [entryPoints.web]
        address = ":80"
        [entryPoints.web.http]
            [entryPoints.web.http.redirections]
                [entryPoints.web.http.redirections.entryPoint]
                    to = "websecure"
                    scheme = "https"

    [entryPoints.websecure]
        address = ":443"

[log]

[accessLog]




# [frontends]
#   [frontends.traefik]
#     backend = "traefik"
#     [frontends.traefik.routes.test_1]
#         rule = "Host:traefik.aikopipo.de"
#   [frontends.nodejs]
#     backend = "nodejs"
#     passHostHeader = true
#     [frontends.nodejs.routes.test_1]
#         rule = "Host:aikopipo.de"
#     [frontends.nodejs.passTLSClientCert]
#         pem = true

[api]
    dashboard = true

[http]
    [http.routers]
        # [http.routers.traefik]
        #     rule = "Host(`traefik.aikopipo.de`)"
        #     service = "traefik"
        # [http.routers.nodejs]
        #     rule = "Host(`aikopipo.de`)"
        #     service = "nodejs"
        [http.routers.my-api]
            rule = "Host(`traefik.aikopipo.de`)"
            service = "api@internal"
            middlewares = ["auth"]

    [http.middlewares.auth.basicAuth]
        users = ["ubuntu:$apr1$hSUuL0gz$Ux0.27vof2P4297HK78P9/"]

    # [http.services]
        # [http.services.traefik.loadBalancer]
        #     [[http.servicestraefik.loadBalancer.servers]]
        #         url = "https://traefik.aikopipo.de:8080/"
        # [http.services.nodejs.loadBalancer]
        #     [[http.servicestraefik.loadBalancer.servers]]
        #         url = "http://aikopipo.de:8443/"


# [backends]
#   [backends.traefik]
#     # traefik dashboard
#     [backends.backend1.servers.server1]
#     url = "https://traefik.aikopipo.de:8080"
#     weight = 1
#   [backends.nodejs]
#     # nodeJS server
#     [backends.backend2.servers.server1]
#     url = "http://aikopipo.de:8443"
#     weight = 1

# [providers.http]
#   endpoint = "http://aikopipo.de:8030"
# [providers.file]
# filename = "/home/ubuntu/TraefikConfig/services.toml"

#Enable retry sending a request if the network error
# [retry]

#Define Docker Backend Configuration
[docker]
    domain = "traefik.aikopipo.de"
    endpoint = "unix:///var/run/docker.sock"
    exposedbydefault = false
    watch = true

#Letsencrypt Registration
#Define the Letsencrypt ACME HTTP challenge
[acme]
    # OnHostRule = true
    email = "aiko.pipo@hotmail.de"
    entryPoint = "websecure"
    storage = "acme.json"
    [acme.httpChallenge]
        entryPoint = "http"
    # [acme.dnsChallenge]
    #     provider = "digitalocean"
    #     delayBeforeCheck = 0
    # [[acme.domains]]
    #     main = "*.aikopipo.de"
